// Dummy activities data based on construction project analysis
export const dummyActivitiesData = [
  {
    "id": 1,
    "taskName": "Geo tech Survey (Soil test, ERT)",
    "status": "Completed",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 151,
    "completedQuantity": 151,
    "plannedStartDate": "2024-12-15",
    "plannedEndDate": "2025-01-14",
    "actualStartDate": "2024-02-03",
    "actualEndDate": "2024-02-03",
    "completionPercentage": 100,
    "daysToComplete": 30,
    "remarks": "Work Completed"
  },
  {
    "id": 2,
    "taskName": "Contour Survey",
    "status": "Completed",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 1,
    "completedQuantity": 1,
    "plannedStartDate": "2024-12-15",
    "plannedEndDate": "2025-01-14",
    "actualStartDate": "2025-02-15",
    "actualEndDate": "2025-02-15",
    "completionPercentage": 100,
    "daysToComplete": 30,
    "remarks": "Work Completed"
  },
  {
    "id": 3,
    "taskName": "Hydrology Survey & Topographical",
    "status": "Completed",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 1,
    "completedQuantity": 1,
    "plannedStartDate": "2025-02-11",
    "plannedEndDate": "2025-02-15",
    "actualStartDate": "2024-02-11",
    "actualEndDate": "2024-02-11",
    "completionPercentage": 100,
    "daysToComplete": 4,
    "remarks": "Work Completed"
  },
  {
    "id": 4,
    "taskName": "Pullout & Lateral Pile Casting",
    "status": "Completed",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 1,
    "completedQuantity": 1,
    "plannedStartDate": "2025-02-09",
    "plannedEndDate": "2025-02-11",
    "actualStartDate": "2025-02-09",
    "actualEndDate": "2024-03-05",
    "completionPercentage": 100,
    "daysToComplete": 2,
    "remarks": "Work Completed"
  },
  {
    "id": 5,
    "taskName": "Land Grading",
    "status": "WIP",
    "category": "Service",
    "uom": "Acr.",
    "totalQuantity": 450,
    "completedQuantity": 150,
    "plannedStartDate": "2025-02-03",
    "plannedEndDate": "2025-02-18",
    "actualStartDate": "2025-02-03",
    "actualEndDate": null,
    "completionPercentage": 33.33,
    "daysToComplete": 15,
    "remarks": "In Progress"
  },
  {
    "id": 6,
    "taskName": "Pile Marking",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "MWp",
    "totalQuantity": 405,
    "completedQuantity": 0,
    "plannedStartDate": "2025-03-22",
    "plannedEndDate": "2025-05-04",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 43,
    "remarks": "Augur & surveyor team required"
  },
  {
    "id": 7,
    "taskName": "MMS Pile Augering",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "MWp",
    "totalQuantity": 405,
    "completedQuantity": 0,
    "plannedStartDate": "2025-03-27",
    "plannedEndDate": "2025-05-24",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 58,
    "remarks": "Pending pile marking completion"
  },
  {
    "id": 8,
    "taskName": "Pile Casting",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "MWp",
    "totalQuantity": 405,
    "completedQuantity": 0,
    "plannedStartDate": "2025-04-02",
    "plannedEndDate": "2025-05-30",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 58,
    "remarks": "Waiting for augering completion"
  },
  {
    "id": 9,
    "taskName": "Solar Panel Procurement",
    "status": "WIP",
    "category": "Supply",
    "uom": "MWp",
    "totalQuantity": 405,
    "completedQuantity": 120,
    "plannedStartDate": "2025-01-15",
    "plannedEndDate": "2025-03-15",
    "actualStartDate": "2025-01-20",
    "actualEndDate": null,
    "completionPercentage": 29.63,
    "daysToComplete": 60,
    "remarks": "Vendor coordination in progress"
  },
  {
    "id": 10,
    "taskName": "Inverter Installation",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "Units",
    "totalQuantity": 45,
    "completedQuantity": 0,
    "plannedStartDate": "2025-04-15",
    "plannedEndDate": "2025-06-15",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 61,
    "remarks": "Pending foundation completion"
  },
  {
    "id": 11,
    "taskName": "Cable Laying - DC",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "Km",
    "totalQuantity": 25,
    "completedQuantity": 0,
    "plannedStartDate": "2025-05-01",
    "plannedEndDate": "2025-06-30",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 60,
    "remarks": "Material procurement pending"
  },
  {
    "id": 12,
    "taskName": "Transformer Installation",
    "status": "WIP",
    "category": "Supply",
    "uom": "Units",
    "totalQuantity": 12,
    "completedQuantity": 3,
    "plannedStartDate": "2025-02-01",
    "plannedEndDate": "2025-04-01",
    "actualStartDate": "2025-02-10",
    "actualEndDate": null,
    "completionPercentage": 25,
    "daysToComplete": 60,
    "remarks": "Site preparation ongoing"
  },
  {
    "id": 13,
    "taskName": "Grid Connection Work",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 1,
    "completedQuantity": 0,
    "plannedStartDate": "2025-06-01",
    "plannedEndDate": "2025-07-15",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 45,
    "remarks": "Utility approval pending"
  },
  {
    "id": 14,
    "taskName": "Control Room Setup",
    "status": "WIP",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 1,
    "completedQuantity": 0.6,
    "plannedStartDate": "2025-03-01",
    "plannedEndDate": "2025-04-15",
    "actualStartDate": "2025-03-05",
    "actualEndDate": null,
    "completionPercentage": 60,
    "daysToComplete": 45,
    "remarks": "Civil work completed, equipment pending"
  },
  {
    "id": 15,
    "taskName": "Testing & Commissioning",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "MWp",
    "totalQuantity": 405,
    "completedQuantity": 0,
    "plannedStartDate": "2025-07-01",
    "plannedEndDate": "2025-08-15",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 45,
    "remarks": "Final phase activity"
  },
  {
    "id": 16,
    "taskName": "1 Geo tech Survey (Soil test, ERT)",
    "status": "Completed",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 151,
    "completedQuantity": 151,
    "plannedStartDate": "2024-12-16",
    "plannedEndDate": "2025-01-15",
    "actualStartDate": "2024-02-04",
    "actualEndDate": "2024-02-04",
    "completionPercentage": 100.0,
    "daysToComplete": 30,
    "remarks": "No remarks"
  },
  {
    "id": 17,
    "taskName": "2 Contour survey",
    "status": "Completed",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 1,
    "completedQuantity": 1,
    "plannedStartDate": "2024-12-16",
    "plannedEndDate": "2025-01-15",
    "actualStartDate": "2025-02-16",
    "actualEndDate": null,
    "completionPercentage": 100.0,
    "daysToComplete": 30,
    "remarks": "No remarks"
  },
  {
    "id": 18,
    "taskName": "3 Hydrology survey & Topographical",
    "status": "Completed",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 1,
    "completedQuantity": 1,
    "plannedStartDate": "2025-02-12",
    "plannedEndDate": "2025-02-16",
    "actualStartDate": "2024-02-12",
    "actualEndDate": "2024-02-12",
    "completionPercentage": 100.0,
    "daysToComplete": 4,
    "remarks": "No remarks"
  },
  {
    "id": 19,
    "taskName": "4 Pullout & Lateral Pile Casting",
    "status": "Completed",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 1,
    "completedQuantity": 1,
    "plannedStartDate": "2025-02-10",
    "plannedEndDate": "2025-02-12",
    "actualStartDate": null,
    "actualEndDate": "2024-03-06",
    "completionPercentage": 100.0,
    "daysToComplete": 2,
    "remarks": "No remarks"
  },
  {
    "id": 20,
    "taskName": "5 Geo tech Survey (Soil test, ERT) reports & documents",
    "status": "Completed",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 1,
    "completedQuantity": 1,
    "plannedStartDate": "2025-02-07",
    "plannedEndDate": "2025-02-11",
    "actualStartDate": null,
    "actualEndDate": "2024-02-21",
    "completionPercentage": 100.0,
    "daysToComplete": 4,
    "remarks": "No remarks"
  },
  {
    "id": 21,
    "taskName": "6 Contour survey reports",
    "status": "Completed",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 1,
    "completedQuantity": 1,
    "plannedStartDate": "2025-02-12",
    "plannedEndDate": "2025-02-17",
    "actualStartDate": "2024-02-19",
    "actualEndDate": "2024-02-19",
    "completionPercentage": 100.0,
    "daysToComplete": 5,
    "remarks": "No remarks"
  },
  {
    "id": 22,
    "taskName": "7 Pullout & Lateral Testing",
    "status": "Completed",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 1,
    "completedQuantity": 1,
    "plannedStartDate": "2025-03-14",
    "plannedEndDate": "2025-03-16",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 100.0,
    "daysToComplete": 2,
    "remarks": "No remarks"
  },
  {
    "id": 23,
    "taskName": "8 Hydrology survey reports",
    "status": "Completed",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 1,
    "completedQuantity": 1,
    "plannedStartDate": "2025-02-12",
    "plannedEndDate": "2025-02-16",
    "actualStartDate": "2024-02-19",
    "actualEndDate": "2024-02-19",
    "completionPercentage": 100.0,
    "daysToComplete": 4,
    "remarks": "No remarks"
  },
  {
    "id": 24,
    "taskName": "9 Land Grading",
    "status": "WIP",
    "category": "Service",
    "uom": "Acr.",
    "totalQuantity": 450,
    "completedQuantity": 150,
    "plannedStartDate": "2025-02-04",
    "plannedEndDate": "2025-02-19",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 33.33,
    "daysToComplete": 15,
    "remarks": "No remarks"
  },
  {
    "id": 25,
    "taskName": "10 Pile Marking",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "MWp",
    "totalQuantity": 405,
    "completedQuantity": 0,
    "plannedStartDate": "2025-03-23",
    "plannedEndDate": "2025-05-05",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0.0,
    "daysToComplete": 43,
    "remarks": "No remarks"
  },
  {
    "id": 26,
    "taskName": "11 MMS Pile Augouring ",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "MWp",
    "totalQuantity": 405,
    "completedQuantity": 0,
    "plannedStartDate": "2025-03-28",
    "plannedEndDate": "2025-05-25",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0.0,
    "daysToComplete": 58,
    "remarks": "No remarks"
  },
  {
    "id": 27,
    "taskName": "12 Pile casting ",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "MWp",
    "totalQuantity": 405,
    "completedQuantity": 0,
    "plannedStartDate": "2025-04-03",
    "plannedEndDate": "2025-05-31",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0.0,
    "daysToComplete": 58,
    "remarks": "No remarks"
  },
  {
    "id": 28,
    "taskName": "13 Pile caping ",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "MWp",
    "totalQuantity": 405,
    "completedQuantity": 0,
    "plannedStartDate": "2025-04-08",
    "plannedEndDate": "2025-06-05",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0.0,
    "daysToComplete": 58,
    "remarks": "No remarks"
  },
  {
    "id": 29,
    "taskName": "14 Pile aligment ",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "MWp",
    "totalQuantity": 405,
    "completedQuantity": 0,
    "plannedStartDate": "2025-04-02",
    "plannedEndDate": "2025-05-30",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0.0,
    "daysToComplete": 58,
    "remarks": "No remarks"
  },
  {
    "id": 30,
    "taskName": "15 1st Layer - Road",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "KM",
    "totalQuantity": 19,
    "completedQuantity": 0,
    "plannedStartDate": "2025-03-01",
    "plannedEndDate": "2025-05-15",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0.0,
    "daysToComplete": 75,
    "remarks": "Grading done on 8.5 KM road and rolling done on 8 KM road  "
  },
  {
    "id": 31,
    "taskName": "16 2nd Layer",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "Km",
    "totalQuantity": 19,
    "completedQuantity": 0,
    "plannedStartDate": "2025-03-31",
    "plannedEndDate": "2025-06-15",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0.0,
    "daysToComplete": 76,
    "remarks": "No remarks"
  },
  {
    "id": 32,
    "taskName": "17 Pole Excavation For fencing",
    "status": "WIP",
    "category": "Service",
    "uom": "Mtr.",
    "totalQuantity": 11,
    "completedQuantity": 1,
    "plannedStartDate": "2025-02-12",
    "plannedEndDate": "2025-04-28",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 9.09,
    "daysToComplete": 75,
    "remarks": "No remarks"
  },
  {
    "id": 33,
    "taskName": "18 Pole Cast ",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "Mtr.",
    "totalQuantity": 0,
    "completedQuantity": 0,
    "plannedStartDate": "2025-03-14",
    "plannedEndDate": "2025-04-28",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 45,
    "remarks": "No remarks"
  },
  {
    "id": 34,
    "taskName": "MMS (Tracker)",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "MWp",
    "totalQuantity": 405,
    "completedQuantity": 0,
    "plannedStartDate": null,
    "plannedEndDate": null,
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0.0,
    "daysToComplete": null,
    "remarks": "Yet to start/Pending"
  },
  {
    "id": 35,
    "taskName": "Module (610 wp)",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "No's",
    "totalQuantity": 663936,
    "completedQuantity": 0,
    "plannedStartDate": null,
    "plannedEndDate": null,
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0.0,
    "daysToComplete": null,
    "remarks": "Yet to start/Pending"
  },
  {
    "id": 36,
    "taskName": "Central Inverter",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "No's",
    "totalQuantity": 96,
    "completedQuantity": 0,
    "plannedStartDate": null,
    "plannedEndDate": null,
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0.0,
    "daysToComplete": null,
    "remarks": "Yet to start/Pending"
  },
  {
    "id": 37,
    "taskName": "13.2 MVA Inverter Duty Transformer",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "No's",
    "totalQuantity": 24,
    "completedQuantity": 0,
    "plannedStartDate": null,
    "plannedEndDate": null,
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0.0,
    "daysToComplete": null,
    "remarks": "Yet to start/Pending"
  },
  {
    "id": 38,
    "taskName": "6.6 MVA Inverter Duty Transformer",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "No's",
    "totalQuantity": 6,
    "completedQuantity": 0,
    "plannedStartDate": null,
    "plannedEndDate": null,
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0.0,
    "daysToComplete": null,
    "remarks": "Yet to start/Pending"
  },
  {
    "id": 39,
    "taskName": "33KV ICOG VCB Panel",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "Units",
    "totalQuantity": 0,
    "completedQuantity": 0,
    "plannedStartDate": null,
    "plannedEndDate": null,
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": null,
    "remarks": "Yet to start/Pending"
  },
  {
    "id": 40,
    "taskName": "MC4 Connectors",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "Units",
    "totalQuantity": 0,
    "completedQuantity": 0,
    "plannedStartDate": null,
    "plannedEndDate": null,
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": null,
    "remarks": "Yet to start/Pending"
  },
  {
    "id": 41,
    "taskName": "Y Connectors",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "Units",
    "totalQuantity": 0,
    "completedQuantity": 0,
    "plannedStartDate": null,
    "plannedEndDate": null,
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": null,
    "remarks": "Yet to start/Pending"
  },
  {
    "id": 42,
    "taskName": "DWC Pipes",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "Units",
    "totalQuantity": 0,
    "completedQuantity": 0,
    "plannedStartDate": null,
    "plannedEndDate": null,
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": null,
    "remarks": "Yet to start/Pending"
  },
  {
    "id": 43,
    "taskName": "Fencing",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "Units",
    "totalQuantity": 0,
    "completedQuantity": 0,
    "plannedStartDate": null,
    "plannedEndDate": null,
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": null,
    "remarks": "Yet to start/Pending"
  },
  {
    "id": 44,
    "taskName": "1C 6 Sqmm Cu DC String Cable",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "Units",
    "totalQuantity": 0,
    "completedQuantity": 0,
    "plannedStartDate": null,
    "plannedEndDate": null,
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": null,
    "remarks": "Yet to start/Pending"
  },
  {
    "id": 45,
    "taskName": "3C * 25 Sq mm Cable (Aux) Al",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "Units",
    "totalQuantity": 0,
    "completedQuantity": 0,
    "plannedStartDate": null,
    "plannedEndDate": null,
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": null,
    "remarks": "Yet to start/Pending"
  },
  {
    "id": 46,
    "taskName": "3C 300 Sqmm Alu LTAC Power Cable 1.9 KV",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "Units",
    "totalQuantity": 0,
    "completedQuantity": 0,
    "plannedStartDate": null,
    "plannedEndDate": null,
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": null,
    "remarks": "Yet to start/Pending"
  },
  {
    "id": 47,
    "taskName": "4C* 120 sq mm Al Arm Cable (Aux)",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "Units",
    "totalQuantity": 0,
    "completedQuantity": 0,
    "plannedStartDate": null,
    "plannedEndDate": null,
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": null,
    "remarks": "Yet to start/Pending"
  },
  {
    "id": 48,
    "taskName": "3C 240 Sqmm Alu HT AC Power Cable 33 KV",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "Units",
    "totalQuantity": 0,
    "completedQuantity": 0,
    "plannedStartDate": null,
    "plannedEndDate": null,
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": null,
    "remarks": "Yet to start/Pending"
  },
  {
    "id": 49,
    "taskName": "3C 185 sqmm AC HT Cable upto PSS",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "Units",
    "totalQuantity": 0,
    "completedQuantity": 0,
    "plannedStartDate": null,
    "plannedEndDate": null,
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": null,
    "remarks": "Yet to start/Pending"
  },
  {
    "id": 50,
    "taskName": "Unknown Procurement Task",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "Units",
    "totalQuantity": 0,
    "completedQuantity": 0,
    "plannedStartDate": null,
    "plannedEndDate": null,
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": null,
    "remarks": "Yet to start/Pending"
  },
   {
    "id": 51,
    "taskName": "Activity 51 Waste Management Implementation",
    "status": "Completed",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 977,
    "completedQuantity": 977,
    "plannedStartDate": "2025-08-05",
    "plannedEndDate": "2026-01-01",
    "actualStartDate": "2025-08-12",
    "actualEndDate": "2026-01-01",
    "completionPercentage": 100,
    "daysToComplete": 149,
    "remarks": "Work completed successfully."
  },
  {
    "id": 52,
    "taskName": "Activity 52 Road Paving",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "KM",
    "totalQuantity": 662,
    "completedQuantity": 0,
    "plannedStartDate": "2025-07-19",
    "plannedEndDate": "2025-10-12",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 85,
    "remarks": "Scheduled for next quarter."
  },
  {
    "id": 53,
    "taskName": "Activity 53 Civil Foundation Work",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "Mtr.",
    "totalQuantity": 632,
    "completedQuantity": 0,
    "plannedStartDate": "2025-08-30",
    "plannedEndDate": "2026-01-31",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 154,
    "remarks": "Scheduled for next quarter."
  },
  {
    "id": 54,
    "taskName": "Activity 54 Cement Delivery",
    "status": "WIP",
    "category": "Supply",
    "uom": "Unit",
    "totalQuantity": 636,
    "completedQuantity": 279,
    "plannedStartDate": "2025-07-07",
    "plannedEndDate": "2025-11-15",
    "actualStartDate": "2025-07-15",
    "actualEndDate": null,
    "completionPercentage": 43.87,
    "daysToComplete": 131,
    "remarks": "Work continuing as planned."
  },
  {
    "id": 55,
    "taskName": "Activity 55 Site Demolition",
    "status": "Completed",
    "category": "Service",
    "uom": "Mtr.",
    "totalQuantity": 7,
    "completedQuantity": 7,
    "plannedStartDate": "2025-06-10",
    "plannedEndDate": "2025-12-04",
    "actualStartDate": "2025-05-31",
    "actualEndDate": "2025-11-26",
    "completionPercentage": 100,
    "daysToComplete": 177,
    "remarks": "Work completed successfully."
  },
  {
    "id": 56,
    "taskName": "Activity 56 Excavation Work",
    "status": "Completed",
    "category": "Service",
    "uom": "Sq.m",
    "totalQuantity": 929,
    "completedQuantity": 929,
    "plannedStartDate": "2025-08-04",
    "plannedEndDate": "2025-10-01",
    "actualStartDate": "2025-08-09",
    "actualEndDate": "2025-09-27",
    "completionPercentage": 100,
    "daysToComplete": 58,
    "remarks": "Work completed successfully."
  },
  {
    "id": 57,
    "taskName": "Activity 57 Structural Erection",
    "status": "WIP",
    "category": "Service",
    "uom": "Mtr.",
    "totalQuantity": 987,
    "completedQuantity": 252,
    "plannedStartDate": "2025-07-04",
    "plannedEndDate": "2025-08-06",
    "actualStartDate": "2025-07-06",
    "actualEndDate": null,
    "completionPercentage": 25.53,
    "daysToComplete": 33,
    "remarks": "Equipment mobilization in progress."
  },
  {
    "id": 58,
    "taskName": "Activity 58 Drainage System Work",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "KM",
    "totalQuantity": 372,
    "completedQuantity": 0,
    "plannedStartDate": "2025-08-01",
    "plannedEndDate": "2026-01-06",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 158,
    "remarks": "Scheduled for next quarter."
  },
  {
    "id": 59,
    "taskName": "Activity 59 Drainage System Work",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "Unit",
    "totalQuantity": 843,
    "completedQuantity": 0,
    "plannedStartDate": "2025-08-27",
    "plannedEndDate": "2025-12-16",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 111,
    "remarks": "Scheduled for next quarter."
  },
  {
    "id": 60,
    "taskName": "Activity 60 Electrical Wiring",
    "status": "Completed",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 50,
    "completedQuantity": 50,
    "plannedStartDate": "2025-06-11",
    "plannedEndDate": "2025-11-25",
    "actualStartDate": "2025-06-19",
    "actualEndDate": "2025-11-27",
    "completionPercentage": 100,
    "daysToComplete": 167,
    "remarks": "Work completed successfully."
  },
  {
    "id": 61,
    "taskName": "Activity 61 Landscaping",
    "status": "WIP",
    "category": "Service",
    "uom": "Sq.m",
    "totalQuantity": 582,
    "completedQuantity": 546,
    "plannedStartDate": "2025-06-25",
    "plannedEndDate": "2025-11-13",
    "actualStartDate": "2025-06-25",
    "actualEndDate": null,
    "completionPercentage": 93.81,
    "daysToComplete": 141,
    "remarks": "Ongoing, minor delays."
  },
  {
    "id": 62,
    "taskName": "Activity 62 Water Pump Procurement",
    "status": "Completed",
    "category": "Supply",
    "uom": "Unit",
    "totalQuantity": 609,
    "completedQuantity": 609,
    "plannedStartDate": "2025-07-28",
    "plannedEndDate": "2026-01-22",
    "actualStartDate": "2025-08-03",
    "actualEndDate": "2026-01-09",
    "completionPercentage": 100,
    "daysToComplete": 178,
    "remarks": "Work completed successfully."
  },
  {
    "id": 63,
    "taskName": "Activity 63 Landscaping",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "KM",
    "totalQuantity": 608,
    "completedQuantity": 0,
    "plannedStartDate": "2025-07-23",
    "plannedEndDate": "2026-01-04",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 165,
    "remarks": "Scheduled for next quarter."
  },
  {
    "id": 64,
    "taskName": "Activity 64 Solar Inverter Supply",
    "status": "WIP",
    "category": "Supply",
    "uom": "Ton",
    "totalQuantity": 50,
    "completedQuantity": 27,
    "plannedStartDate": "2025-06-22",
    "plannedEndDate": "2025-09-17",
    "actualStartDate": "2025-06-24",
    "actualEndDate": null,
    "completionPercentage": 54.0,
    "daysToComplete": 87,
    "remarks": "In progress, awaiting material."
  },
  {
    "id": 65,
    "taskName": "Activity 65 Control Panel Supply",
    "status": "WIP",
    "category": "Supply",
    "uom": "Unit",
    "totalQuantity": 530,
    "completedQuantity": 353,
    "plannedStartDate": "2025-08-01",
    "plannedEndDate": "2026-01-20",
    "actualStartDate": "2025-08-09",
    "actualEndDate": null,
    "completionPercentage": 66.6,
    "daysToComplete": 172,
    "remarks": "Ongoing, minor delays."
  },
  {
    "id": 66,
    "taskName": "Activity 66 Control Panel Supply",
    "status": "WIP",
    "category": "Supply",
    "uom": "Km",
    "totalQuantity": 776,
    "completedQuantity": 303,
    "plannedStartDate": "2025-07-06",
    "plannedEndDate": "2025-11-24",
    "actualStartDate": "2025-07-16",
    "actualEndDate": null,
    "completionPercentage": 39.05,
    "daysToComplete": 141,
    "remarks": "Ongoing, minor delays."
  },
  {
    "id": 67,
    "taskName": "Activity 67 Waste Management Implementation",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "Unit",
    "totalQuantity": 139,
    "completedQuantity": 0,
    "plannedStartDate": "2025-08-25",
    "plannedEndDate": "2025-12-07",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 104,
    "remarks": "Resource allocation in progress."
  },
  {
    "id": 68,
    "taskName": "Activity 68 Fire Fighting System Setup",
    "status": "Completed",
    "category": "Service",
    "uom": "Mtr.",
    "totalQuantity": 727,
    "completedQuantity": 727,
    "plannedStartDate": "2025-08-01",
    "plannedEndDate": "2026-01-28",
    "actualStartDate": "2025-07-28",
    "actualEndDate": "2026-01-20",
    "completionPercentage": 100,
    "daysToComplete": 180,
    "remarks": "Work completed successfully."
  },
  {
    "id": 69,
    "taskName": "Activity 69 Security System Installation",
    "status": "Completed",
    "category": "Service",
    "uom": "Sq.m",
    "totalQuantity": 696,
    "completedQuantity": 696,
    "plannedStartDate": "2025-06-05",
    "plannedEndDate": "2025-09-09",
    "actualStartDate": "2025-06-03",
    "actualEndDate": "2025-09-24",
    "completionPercentage": 100,
    "daysToComplete": 96,
    "remarks": "Work completed successfully."
  },
  {
    "id": 70,
    "taskName": "Activity 70 Cable & Wire Supply",
    "status": "WIP",
    "category": "Supply",
    "uom": "Ton",
    "totalQuantity": 204,
    "completedQuantity": 139,
    "plannedStartDate": "2025-07-28",
    "plannedEndDate": "2025-10-09",
    "actualStartDate": "2025-07-23",
    "actualEndDate": null,
    "completionPercentage": 68.14,
    "daysToComplete": 73,
    "remarks": "In progress, awaiting material."
  },
    {
    "id": 71,
    "taskName": "Activity 71 HVAC Installation",
    "status": "WIP",
    "category": "Service",
    "uom": "Unit",
    "totalQuantity": 450,
    "completedQuantity": 200,
    "plannedStartDate": "2025-09-01",
    "plannedEndDate": "2026-02-28",
    "actualStartDate": "2025-09-05",
    "actualEndDate": null,
    "completionPercentage": 44.44,
    "daysToComplete": 180,
    "remarks": "In progress, awaiting material."
  },
  {
    "id": 72,
    "taskName": "Activity 72 Building Material Supply",
    "status": "Completed",
    "category": "Supply",
    "uom": "Ton",
    "totalQuantity": 1500,
    "completedQuantity": 1500,
    "plannedStartDate": "2025-08-10",
    "plannedEndDate": "2025-11-30",
    "actualStartDate": "2025-08-12",
    "actualEndDate": "2025-11-25",
    "completionPercentage": 100,
    "daysToComplete": 112,
    "remarks": "Work completed successfully."
  },
  {
    "id": 73,
    "taskName": "Activity 73 Site Demolition",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 1,
    "completedQuantity": 0,
    "plannedStartDate": "2025-10-15",
    "plannedEndDate": "2025-11-15",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 31,
    "remarks": "Pending approvals."
  },
  {
    "id": 74,
    "taskName": "Activity 74 Lighting Fixture Supply",
    "status": "WIP",
    "category": "Supply",
    "uom": "Set",
    "totalQuantity": 250,
    "completedQuantity": 120,
    "plannedStartDate": "2025-09-05",
    "plannedEndDate": "2026-01-05",
    "actualStartDate": "2025-09-10",
    "actualEndDate": null,
    "completionPercentage": 48.0,
    "daysToComplete": 122,
    "remarks": "Ongoing, minor delays."
  },
  {
    "id": 75,
    "taskName": "Activity 75 Plumbing System",
    "status": "Completed",
    "category": "Service",
    "uom": "Mtr.",
    "totalQuantity": 800,
    "completedQuantity": 800,
    "plannedStartDate": "2025-07-20",
    "plannedEndDate": "2025-10-20",
    "actualStartDate": "2025-07-22",
    "actualEndDate": "2025-10-18",
    "completionPercentage": 100,
    "daysToComplete": 92,
    "remarks": "Work completed successfully."
  },
  {
    "id": 76,
    "taskName": "Activity 76 Transformer Delivery",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "Unit",
    "totalQuantity": 15,
    "completedQuantity": 0,
    "plannedStartDate": "2025-11-01",
    "plannedEndDate": "2026-01-31",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 91,
    "remarks": "Awaiting site clearance."
  },
  {
    "id": 77,
    "taskName": "Activity 77 Electrical Wiring",
    "status": "WIP",
    "category": "Service",
    "uom": "KM",
    "totalQuantity": 50,
    "completedQuantity": 25,
    "plannedStartDate": "2025-08-20",
    "plannedEndDate": "2025-12-20",
    "actualStartDate": "2025-08-25",
    "actualEndDate": null,
    "completionPercentage": 50.0,
    "daysToComplete": 122,
    "remarks": "Equipment mobilization in progress."
  },
  {
    "id": 78,
    "taskName": "Activity 78 Structural Steel Procurement",
    "status": "Completed",
    "category": "Supply",
    "uom": "Ton",
    "totalQuantity": 2000,
    "completedQuantity": 2000,
    "plannedStartDate": "2025-07-10",
    "plannedEndDate": "2025-10-10",
    "actualStartDate": "2025-07-15",
    "actualEndDate": "2025-10-05",
    "completionPercentage": 100,
    "daysToComplete": 92,
    "remarks": "Work completed successfully."
  },
  {
    "id": 79,
    "taskName": "Activity 79 Road Paving",
    "status": "WIP",
    "category": "Service",
    "uom": "KM",
    "totalQuantity": 10,
    "completedQuantity": 3,
    "plannedStartDate": "2025-09-10",
    "plannedEndDate": "2025-12-10",
    "actualStartDate": "2025-09-12",
    "actualEndDate": null,
    "completionPercentage": 30.0,
    "daysToComplete": 91,
    "remarks": "Ongoing, minor delays."
  },
  {
    "id": 80,
    "taskName": "Activity 80 Security Camera Procurement",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "Unit",
    "totalQuantity": 120,
    "completedQuantity": 0,
    "plannedStartDate": "2025-10-01",
    "plannedEndDate": "2026-01-01",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 92,
    "remarks": "Resource allocation in progress."
  },
  {
    "id": 81,
    "taskName": "Activity 81 Interior Finishing",
    "status": "Completed",
    "category": "Service",
    "uom": "Sq.m",
    "totalQuantity": 1200,
    "completedQuantity": 1200,
    "plannedStartDate": "2025-08-01",
    "plannedEndDate": "2025-11-01",
    "actualStartDate": "2025-08-05",
    "actualEndDate": "2025-10-28",
    "completionPercentage": 100,
    "daysToComplete": 92,
    "remarks": "Work completed successfully."
  },
  {
    "id": 82,
    "taskName": "Activity 82 Piping Material Procurement",
    "status": "WIP",
    "category": "Supply",
    "uom": "Mtr.",
    "totalQuantity": 3000,
    "completedQuantity": 1500,
    "plannedStartDate": "2025-09-15",
    "plannedEndDate": "2026-03-15",
    "actualStartDate": "2025-09-20",
    "actualEndDate": null,
    "completionPercentage": 50.0,
    "daysToComplete": 181,
    "remarks": "In progress, awaiting material."
  },
  {
    "id": 83,
    "taskName": "Activity 83 Access Control System",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "Unit",
    "totalQuantity": 5,
    "completedQuantity": 0,
    "plannedStartDate": "2025-11-20",
    "plannedEndDate": "2026-01-20",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 61,
    "remarks": "Scheduled for next quarter."
  },
  {
    "id": 84,
    "taskName": "Activity 84 Battery Storage System Procurement",
    "status": "Completed",
    "category": "Supply",
    "uom": "Set",
    "totalQuantity": 50,
    "completedQuantity": 50,
    "plannedStartDate": "2025-07-01",
    "plannedEndDate": "2025-09-30",
    "actualStartDate": "2025-07-03",
    "actualEndDate": "2025-09-28",
    "completionPercentage": 100,
    "daysToComplete": 91,
    "remarks": "Work completed successfully."
  },
  {
    "id": 85,
    "taskName": "Activity 85 Fire Fighting System Setup",
    "status": "WIP",
    "category": "Service",
    "uom": "Unit",
    "totalQuantity": 30,
    "completedQuantity": 15,
    "plannedStartDate": "2025-08-25",
    "plannedEndDate": "2025-11-25",
    "actualStartDate": "2025-08-28",
    "actualEndDate": null,
    "completionPercentage": 50.0,
    "daysToComplete": 92,
    "remarks": "Ongoing, minor delays."
  },
  {
    "id": 86,
    "taskName": "Activity 86 HVAC Equipment Supply",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "Unit",
    "totalQuantity": 75,
    "completedQuantity": 0,
    "plannedStartDate": "2025-10-01",
    "plannedEndDate": "2026-02-01",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 123,
    "remarks": "Pending approvals."
  },
  {
    "id": 87,
    "taskName": "Activity 87 Drainage System Work",
    "status": "Completed",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 1,
    "completedQuantity": 1,
    "plannedStartDate": "2025-07-15",
    "plannedEndDate": "2025-09-15",
    "actualStartDate": "2025-07-18",
    "actualEndDate": "2025-09-10",
    "completionPercentage": 100,
    "daysToComplete": 62,
    "remarks": "Work completed successfully."
  },
  {
    "id": 88,
    "taskName": "Activity 88 Switchgear Supply",
    "status": "WIP",
    "category": "Supply",
    "uom": "Unit",
    "totalQuantity": 40,
    "completedQuantity": 10,
    "plannedStartDate": "2025-09-20",
    "plannedEndDate": "2026-01-20",
    "actualStartDate": "2025-09-25",
    "actualEndDate": null,
    "completionPercentage": 25.0,
    "daysToComplete": 122,
    "remarks": "In progress, awaiting material."
  },
  {
    "id": 89,
    "taskName": "Activity 89 Waste Management Implementation",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "Sq.m",
    "totalQuantity": 200,
    "completedQuantity": 0,
    "plannedStartDate": "2025-12-01",
    "plannedEndDate": "2026-02-28",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 89,
    "remarks": "Resource allocation in progress."
  },
  {
    "id": 90,
    "taskName": "Activity 90 Fire Extinguisher Supply",
    "status": "Completed",
    "category": "Supply",
    "uom": "Unit",
    "totalQuantity": 100,
    "completedQuantity": 100,
    "plannedStartDate": "2025-08-01",
    "plannedEndDate": "2025-10-31",
    "actualStartDate": "2025-08-03",
    "actualEndDate": "2025-10-25",
    "completionPercentage": 100,
    "daysToComplete": 91,
    "remarks": "Work completed successfully."
  },
  {
    "id": 91,
    "taskName": "Activity 91 Electrical Wiring",
    "status": "WIP",
    "category": "Service",
    "uom": "Unit",
    "totalQuantity": 300,
    "completedQuantity": 180,
    "plannedStartDate": "2025-09-10",
    "plannedEndDate": "2026-01-10",
    "actualStartDate": "2025-09-15",
    "actualEndDate": null,
    "completionPercentage": 60.0,
    "daysToComplete": 122,
    "remarks": "Ongoing, minor delays."
  },
  {
    "id": 92,
    "taskName": "Activity 92 Security System Installation",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 1,
    "completedQuantity": 0,
    "plannedStartDate": "2025-11-05",
    "plannedEndDate": "2026-02-05",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 92,
    "remarks": "Awaiting site clearance."
  },
  {
    "id": 93,
    "taskName": "Activity 93 Water Pump Procurement",
    "status": "WIP",
    "category": "Supply",
    "uom": "Unit",
    "totalQuantity": 80,
    "completedQuantity": 35,
    "plannedStartDate": "2025-08-20",
    "plannedEndDate": "2025-12-20",
    "actualStartDate": "2025-08-22",
    "actualEndDate": null,
    "completionPercentage": 43.75,
    "daysToComplete": 122,
    "remarks": "In progress, awaiting material."
  },
  {
    "id": 94,
    "taskName": "Activity 94 Landscaping",
    "status": "Completed",
    "category": "Service",
    "uom": "Sq.m",
    "totalQuantity": 700,
    "completedQuantity": 700,
    "plannedStartDate": "2025-07-25",
    "plannedEndDate": "2025-10-25",
    "actualStartDate": "2025-07-28",
    "actualEndDate": "2025-10-20",
    "completionPercentage": 100,
    "daysToComplete": 92,
    "remarks": "Work completed successfully."
  },
  {
    "id": 95,
    "taskName": "Activity 95 Central Inverter Supply",
    "status": "Yet to start/Pending",
    "category": "Supply",
    "uom": "Unit",
    "totalQuantity": 20,
    "completedQuantity": 0,
    "plannedStartDate": "2025-11-10",
    "plannedEndDate": "2026-02-10",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 92,
    "remarks": "Scheduled for next quarter."
  },
  {
    "id": 96,
    "taskName": "Activity 96 Civil Foundation Work",
    "status": "WIP",
    "category": "Service",
    "uom": "Mtr.",
    "totalQuantity": 500,
    "completedQuantity": 250,
    "plannedStartDate": "2025-09-01",
    "plannedEndDate": "2026-01-31",
    "actualStartDate": "2025-09-03",
    "actualEndDate": null,
    "completionPercentage": 50.0,
    "daysToComplete": 152,
    "remarks": "Equipment mobilization in progress."
  },
  {
    "id": 97,
    "taskName": "Activity 97 Cement Delivery",
    "status": "Completed",
    "category": "Supply",
    "uom": "Bag",
    "totalQuantity": 2500,
    "completedQuantity": 2500,
    "plannedStartDate": "2025-08-05",
    "plannedEndDate": "2025-11-05",
    "actualStartDate": "2025-08-08",
    "actualEndDate": "2025-10-30",
    "completionPercentage": 100,
    "daysToComplete": 92,
    "remarks": "Work completed successfully."
  },
  {
    "id": 98,
    "taskName": "Activity 98 Excavation Work",
    "status": "Yet to start/Pending",
    "category": "Service",
    "uom": "Lot",
    "totalQuantity": 1,
    "completedQuantity": 0,
    "plannedStartDate": "2025-10-20",
    "plannedEndDate": "2025-12-20",
    "actualStartDate": null,
    "actualEndDate": null,
    "completionPercentage": 0,
    "daysToComplete": 61,
    "remarks": "Pending approvals."
  },
  {
    "id": 99,
    "taskName": "Activity 99 Fire Extinguisher Supply",
    "status": "WIP",
    "category": "Supply",
    "uom": "Unit",
    "totalQuantity": 60,
    "completedQuantity": 20,
    "plannedStartDate": "2025-09-25",
    "plannedEndDate": "2026-01-25",
    "actualStartDate": "2025-09-30",
    "actualEndDate": null,
    "completionPercentage": 33.33,
    "daysToComplete": 122,
    "remarks": "Ongoing, minor delays."
  },
  {
    "id": 100,
    "taskName": "Activity 100 Cable & Wire Supply",
    "status": "Completed",
    "category": "Supply",
    "uom": "Km",
    "totalQuantity": 500,
    "completedQuantity": 500,
    "plannedStartDate": "2025-08-15",
    "plannedEndDate": "2025-11-15",
    "actualStartDate": "2025-08-18",
    "actualEndDate": "2025-11-10",
    "completionPercentage": 100,
    "daysToComplete": 92,
    "remarks": "Work completed successfully."
  }
];

// Summary statistics for dashboard
export const getProjectSummary = () => {
  const totalTasks = dummyActivitiesData.length;
  const completedTasks = dummyActivitiesData.filter(task => task.status === "Completed").length;
  const wipTasks = dummyActivitiesData.filter(task => task.status === "WIP").length;
  const pendingTasks = dummyActivitiesData.filter(task => task.status === "Yet to start/Pending").length;
  
  const totalCompletion = dummyActivitiesData.reduce((sum, task) => sum + task.completionPercentage, 0);
  const overallProgress = totalCompletion / totalTasks;
  
  const serviceTasks = dummyActivitiesData.filter(task => task.category === "Service").length;
  const supplyTasks = dummyActivitiesData.filter(task => task.category === "Supply").length;
  
  return {
    totalTasks,
    completedTasks,
    wipTasks,
    pendingTasks,
    overallProgress: overallProgress.toFixed(1),
    serviceTasks,
    supplyTasks
  };
};

// Data for charts
export const getStatusChartData = () => {
  const summary = getProjectSummary();
  return [
    { name: 'Completed', value: summary.completedTasks, color: '#10B981' },
    { name: 'In Progress', value: summary.wipTasks, color: '#F59E0B' },
    { name: 'Pending', value: summary.pendingTasks, color: '#EF4444' }
  ];
};

export const getCategoryChartData = () => {
  const summary = getProjectSummary();
  return [
    { name: 'Service Tasks', value: summary.serviceTasks, color: '#3B82F6' },
    { name: 'Supply Tasks', value: summary.supplyTasks, color: '#8B5CF6' }
  ];
};